// SPDX-FileCopyrightText: © 2026 Alexandros Theodotou <alex@zrythm.org>
// SPDX-License-Identifier: LicenseRef-ZrythmLicense

import QtQuick
import Zrythm

/**
 * Mouse area that edits a numeric value by dragging, optionally pinning the cursor.
 *
 * While dragging and pinCursor is set, the cursor is hidden and warped back to
 * the drag start position after each move event, allowing unbounded adjustment.
 * Drag mechanics (axis locking, Shift+drag fine adjustment, wheel steps and
 * double-click reset) are shared so all value controls feel the same.
 *
 * The host must bind the current value to the value property and apply changes
 * reported through the valueModified signal (e.g., to a processor parameter).
 */
MouseArea {
  id: root

  /// Axes the drag is allowed to affect (Qt.Horizontal, Qt.Vertical, or both)
  property int allowedAxes: Qt.Horizontal | Qt.Vertical

  /// Movement in px required before the drag axis locks and the value starts changing
  property real axisLockThreshold: 3

  /// Value applied on double-click when resetOnDoubleClick is set
  property real defaultValue: 0.5
  readonly property bool dragging: priv.dragging

  /// Sensitivity multiplier while Shift is held during a drag
  property real fineFactor: 0.1
  property real from: 0

  /// Cursor shape while hovering and not dragging (-1 leaves the existing cursor untouched)
  property int hoverCursorShape: -1

  /// Hide and pin the cursor while dragging
  property bool pinCursor: true

  /// Drag distance in px corresponding to a full-range change
  property real pixelsForFullRange: 250
  property bool resetOnDoubleClick: true
  property real to: 1

  /// Current value, bound by the host
  property real value: 0.5

  /// Wheel axis used for value changes (Qt.Vertical or Qt.Horizontal)
  property int wheelAxis: Qt.Vertical

  /// Wheel step as a fraction of the range while Ctrl is held
  property real wheelFineStep: 0.01

  /// Wheel step as a fraction of the range
  property real wheelStep: 0.05

  /// Emitted when a drag ends, either by release or cancellation
  signal dragEnded

  /// Emitted when a drag starts
  signal dragStarted

  /// Emitted when the drag, wheel or double-click requests a new value
  signal valueModified(real newValue)

  function clampValue(v) {
    return Math.max(Math.min(v, Math.max(root.from, root.to)), Math.min(root.from, root.to));
  }

  function endDrag() {
    if (priv.dragging) {
      priv.dragging = false;
      root.dragEnded();
    }
  }

  acceptedButtons: Qt.LeftButton

  // Hide the cursor while dragging (undefined leaves the existing cursor untouched)
  cursorShape: {
    if (priv.dragging && root.pinCursor) {
      return Qt.BlankCursor;
    }
    return root.hoverCursorShape >= 0 ? root.hoverCursorShape : undefined;
  }
  hoverEnabled: true
  preventStealing: true

  onCanceled: {
    endDrag();
  }
  onDoubleClicked: function (mouse) {
    if (root.resetOnDoubleClick && mouse.button === Qt.LeftButton) {
      root.valueModified(root.defaultValue);
    }
  }
  onPositionChanged: function (mouse) {
    if (!priv.dragging) {
      return;
    }

    if (priv.expectWarpEvent) {
      priv.expectWarpEvent = false;

      // Ignore the synthetic move event generated by our own cursor warp (it lands back on the drag start position)
      if (Math.abs(mouse.x - priv.lastCoordinates.x) <= 1 && Math.abs(mouse.y - priv.lastCoordinates.y) <= 1) {
        priv.warpsSinceLastEcho = 0;
        priv.lastMousePos = Qt.point(mouse.x, mouse.y);
        return;
      }

      // Expected warp echo never arrived: the platform may not honor cursor warping (e.g. Wayland), or event compression dropped it - disable warping after repeated misses
      priv.warpsSinceLastEcho += 1;
      if (priv.warpsSinceLastEcho >= 5) {
        priv.warpingEffective = false;
      }
    }

    // Accumulate incremental movement so the drag behaves the same whether or not cursor warping is honored by the platform
    const incX = mouse.x - priv.lastMousePos.x;
    const incY = priv.lastMousePos.y - mouse.y; // Invert Y for natural dragging
    priv.accumulatedDragDeltaX += incX;
    priv.accumulatedDragDeltaY += incY;
    priv.lastMousePos = Qt.point(mouse.x, mouse.y);

    // Lock the drag axis once movement exceeds the threshold
    if (priv.dragAxis === 0 && Math.abs(priv.accumulatedDragDeltaX) + Math.abs(priv.accumulatedDragDeltaY) > root.axisLockThreshold) {
      if (root.allowedAxes === (Qt.Horizontal | Qt.Vertical)) {
        priv.dragAxis = Math.abs(priv.accumulatedDragDeltaY) >= Math.abs(priv.accumulatedDragDeltaX) ? 2 : 1;
      } else {
        priv.dragAxis = root.allowedAxes === Qt.Horizontal ? 1 : 2;
      }
    }

    if (priv.dragAxis !== 0) {
      // Apply the fine factor to incremental movement so toggling Shift mid-drag does not rescale past movement
      const fine = (mouse.modifiers & Qt.ShiftModifier) !== 0 ? root.fineFactor : 1.0;
      const incPx = priv.dragAxis === 1 ? incX : incY;
      priv.valueDelta += incPx / root.pixelsForFullRange * (root.to - root.from) * fine;

      const newValue = clampValue(priv.valueAtStart + priv.valueDelta);
      if (newValue !== root.value) {
        root.valueModified(newValue);
      }
    }

    if (root.pinCursor && priv.warpingEffective) {
      // Recompute the warp target per event so it tracks the control if it moves on screen mid-drag
      CursorManager.warpCursor(root.mapToGlobal(priv.lastCoordinates.x, priv.lastCoordinates.y));
      priv.expectWarpEvent = true;
    }
  }
  onPressed: function (mouse) {
    if (mouse.button === Qt.LeftButton) {
      priv.dragging = true;
      priv.valueAtStart = root.value;
      priv.valueDelta = 0;
      priv.lastCoordinates = Qt.point(mouse.x, mouse.y);
      priv.lastMousePos = priv.lastCoordinates;
      priv.accumulatedDragDeltaX = 0;
      priv.accumulatedDragDeltaY = 0;
      priv.dragAxis = 0;
      priv.expectWarpEvent = false;
      priv.warpingEffective = true;
      priv.warpsSinceLastEcho = 0;
      root.dragStarted();
      mouse.accepted = true;
    }
  }
  onReleased: function (mouse) {
    if (mouse.button === Qt.LeftButton) {
      endDrag();
    }
  }
  onWheel: function (wheel) {
    const angleDelta = root.wheelAxis === Qt.Horizontal ? wheel.angleDelta.x : wheel.angleDelta.y;
    if (angleDelta === 0) {
      return;
    }

    const step = (wheel.modifiers & Qt.ControlModifier ? root.wheelFineStep : root.wheelStep) * (root.to - root.from);
    if (!(step > 0)) {
      // Zero or invalid range: nothing to step through
      return;
    }
    const newValue = clampValue(root.value + (angleDelta > 0 ? step : -step));
    if (newValue !== root.value) {
      root.valueModified(newValue);
    }
    wheel.accepted = true;
  }

  QtObject {
    id: priv

    property real accumulatedDragDeltaX: 0
    property real accumulatedDragDeltaY: 0
    property int dragAxis: 0 // 0 = undecided, 1 = X, 2 = Y
    property bool dragging: false
    property bool expectWarpEvent: false
    property point lastCoordinates: Qt.point(0, 0) // Drag start in local coordinates
    property point lastMousePos: Qt.point(0, 0)
    property real valueAtStart: 0
    property real valueDelta: 0 // Accumulated value change since drag start
    property bool warpingEffective: true
    property int warpsSinceLastEcho: 0
  }
}
