/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    This header file contains configuration options for the plug-in. If you need to change any of
    these, it'd be wise to do so using the Jucer, rather than editing this file directly...

*/

#ifndef __PLUGINCHARACTERISTICS_D4EFFF1A__
#define __PLUGINCHARACTERISTICS_D4EFFF1A__

#define JucePlugin_Name                   "ReFine"
#define JucePlugin_Desc                   "ReFine"
#define JucePlugin_Manufacturer           "Lkjb"
#define JucePlugin_ManufacturerCode       'Lkjb'
#define JucePlugin_PluginCode             'LkRf'
#define JucePlugin_MaxNumInputChannels    2
#define JucePlugin_MaxNumOutputChannels   2
#define JucePlugin_PreferredChannelConfigurations  {1, 1}, {2, 2}
#define JucePlugin_IsSynth                0
#define JucePlugin_IsMidiEffect           0
#define JucePlugin_WantsMidiInput         0
#define JucePlugin_ProducesMidiOutput     0
#define JucePlugin_SilenceInProducesSilenceOut  0
#define JucePlugin_TailLengthSeconds      0
#define JucePlugin_EditorRequiresKeyboardFocus  1
#define JucePlugin_Version                1.1.0
#define JucePlugin_VersionCode            0x10100
#define JucePlugin_VersionString          "1.1.0"
#define JucePlugin_VSTUniqueID            JucePlugin_PluginCode
#define JucePlugin_VSTCategory            kPlugCategEffect
#define JucePlugin_AUMainType             kAudioUnitType_Effect
#define JucePlugin_AUSubType              JucePlugin_PluginCode
#define JucePlugin_AUExportPrefix         ReFineAU
#define JucePlugin_AUExportPrefixQuoted   "ReFineAU"
#define JucePlugin_AUManufacturerCode     JucePlugin_ManufacturerCode
#define JucePlugin_CFBundleIdentifier     com.lkjb.ReFine
#define JucePlugin_AUCocoaViewClassName   PitchedDelayAU_V1
#define JucePlugin_RTASCategory           ePlugInCategory_None
#define JucePlugin_RTASManufacturerCode   JucePlugin_ManufacturerCode
#define JucePlugin_RTASProductId          JucePlugin_PluginCode
#define JucePlugin_RTASDisableBypass      0
#define JucePlugin_RTASDisableMultiMono   0
#define JucePlugin_AAXIdentifier          com.yourcompany.ReFine
#define JucePlugin_AAXManufacturerCode    JucePlugin_ManufacturerCode
#define JucePlugin_AAXProductId           JucePlugin_PluginCode
#define JucePlugin_AAXPluginId            JucePlugin_PluginCode
#define JucePlugin_AAXCategory            AAX_ePlugInCategory_Dynamics
#define JucePlugin_AAXDisableBypass       0

#define JucePlugin_LV2URI               "https://github.com/lkjbdsp/lkjb-plugins#ReFine"
//#define JucePlugin_LV2Category          "DelayPlugin"
#define JucePlugin_WantsLV2Latency      0
#define JucePlugin_WantsLV2State        0
#define JucePlugin_WantsLV2TimePos      0
#define JucePlugin_WantsLV2Presets      0

#endif   // __PLUGINCHARACTERISTICS_D4EFFF1A__
