#!/bin/sh
set -e
# SoX Resampler Library       Copyright (c) 2007-18 robs@users.sourceforge.net
# Licence for this file: LGPL v2.1                  See LICENCE for details.

# Makes the distribution tarball

test $# = 1 -o `git status -s|wc -c` = 0
rm -rf Release
./go -j4
cd Release
make package_source
