// SPDX-FileCopyrightText: © 2026 Alexandros Theodotou <alex@zrythm.org>
// SPDX-License-Identifier: LicenseRef-ZrythmLicense

#pragma once

#include <filesystem>
#include <functional>
#include <memory>
#include <optional>

#include "plugins/plugin.h"

#include <QByteArray>

namespace zrythm::plugins
{

class Lv2World;

/**
 * @brief Native LV2 plugin host implementation.
 *
 * Hosts LV2 plugins directly via lilv. The shared lilv world is injected
 * at construction (throws without one).
 *
 * The instance is created eagerly when the configuration arrives, at the
 * sample rate and block length reported by @p sample_rate_provider and
 * @p buffer_size_provider (falling back to built-in defaults when they
 * are unset). LV2 binds both at instantiation, so processing preparation
 * re-creates the instance when the engine's values differ, carrying the
 * current state over.
 */
class Lv2Plugin : public Plugin
{
  Q_OBJECT
  QML_ELEMENT
  QML_UNCREATABLE ("")

public:
  /**
   * @brief Constructor for Lv2Plugin.
   *
   * @param registry Object registry
   * @param world Shared lilv world (main thread only)
   * @param sample_rate_provider Reports the engine's current sample rate
   * (may be unset)
   * @param buffer_size_provider Reports the engine's current maximum
   * block length (may be unset)
   * @param host_window_factory Factory for creating plugin host windows
   * @param parent Parent QObject
   */
  Lv2Plugin (
    utils::IObjectRegistry                &registry,
    std::shared_ptr<Lv2World>              world,
    std::function<units::sample_rate_t ()> sample_rate_provider = {},
    std::function<units::sample_u32_t ()>  buffer_size_provider = {},
    PluginHostWindowFactory                host_window_factory = {},
    QObject *                              parent = nullptr);
  Q_DISABLE_COPY_MOVE (Lv2Plugin)
  ~Lv2Plugin () override;

  units::sample_u32_t get_single_playback_latency () const override;

protected:
  void prepare_plugin_for_processing (
    units::sample_rate_t sample_rate,
    units::sample_u32_t  max_block_length) override;

  void process_impl (
    dsp::graph::ProcessBlockInfo time_info,
    const dsp::ITransport       &transport,
    const dsp::TempoMap         &tempo_map) noexcept override;

  void release_resources_impl () override;

private Q_SLOTS:
  void on_configuration_changed (
    PluginConfiguration * config,
    bool                  generateNewPluginPortsAndParams);

private:
  /**
   * @brief Resolves and caches the lilv plugin for the current
   * configuration.
   *
   * The plugin is matched by URI hash (the descriptor's unique id) among the
   * bundle's plugins.
   *
   * @param bundle_path Path to the plugin bundle directory.
   * @param uri_hash Hash of the plugin URI, as generated by
   *   get_hash_for_range().
   * @param generate_new Whether to create Zrythm ports and parameters from
   *   the plugin's port metadata.
   */
  bool load_plugin (
    const std::filesystem::path &bundle_path,
    int64_t                      uri_hash,
    bool                         generate_new);
  void unload_current_plugin ();

  /**
   * @brief Creates Zrythm ports and parameters from the plugin's port
   * metadata, or rebuilds the parameter routing for already existing ones.
   */
  void create_ports_and_parameters (bool generate_new);

  /**
   * @brief Applies the pending state to the live instance, keeping it
   * pending when the restore fails.
   */
  void apply_pending_state ();

  std::string save_state_impl () const override;
  bool        load_state_impl (const std::string &base64_state) override;

  static constexpr auto kStateKey = "state"sv;
  friend void           to_json (nlohmann::json &j, const Lv2Plugin &p);
  friend void           from_json (const nlohmann::json &j, Lv2Plugin &p);

  class Lv2PluginImpl;
  std::unique_ptr<Lv2PluginImpl> pimpl_;

  /** Shared lilv world (main thread only). */
  std::shared_ptr<Lv2World> world_;

  /** Reports the engine's current sample rate (may be unset). */
  std::function<units::sample_rate_t ()> sample_rate_provider_;
  /** Reports the engine's current maximum block length (may be unset). */
  std::function<units::sample_u32_t ()> buffer_size_provider_;

  /** Pending state to apply after instantiation (from JSON). */
  std::optional<QByteArray> state_to_apply_;
};

} // namespace zrythm::plugins
