// SPDX-FileCopyrightText: © 2026 Alexandros Theodotou <alex@zrythm.org>
// SPDX-License-Identifier: LicenseRef-ZrythmLicense

#pragma once

#include "plugins/plugin.h"

namespace zrythm::plugins
{

/**
 * @brief Native VST3 plugin host implementation.
 *
 * Hosts VST3 plugins directly via the VST3 SDK's IComponent /
 * IAudioProcessor / IEditController interfaces, mirroring how ClapPlugin
 * hosts CLAP plugins. Discovery is done by Vst3PluginFormat.
 */
class Vst3Plugin : public Plugin
{
  Q_OBJECT
  QML_ELEMENT
  QML_UNCREATABLE ("")

public:
  /**
   * @brief Constructor for Vst3Plugin.
   *
   * @param dependencies Processor dependencies
   * @param host_window_factory Factory for creating plugin host windows
   * @param parent Parent QObject
   */
  Vst3Plugin (
    utils::IObjectRegistry &registry,
    PluginHostWindowFactory host_window_factory,
    QObject *               parent = nullptr);
  Q_DISABLE_COPY_MOVE (Vst3Plugin)
  ~Vst3Plugin () override;

  // ============================================================================
  // Plugin Interface Implementation
  // ============================================================================

  units::sample_u32_t get_single_playback_latency () const override;

  bool hasNativeUi () const override;

protected:
  void prepare_plugin_for_processing (
    units::sample_rate_t sample_rate,
    units::sample_u32_t  max_block_length) override;

  void process_impl (dsp::graph::ProcessBlockInfo time_info) noexcept override;

  void release_resources_impl () override;

private Q_SLOTS:
  /**
   * @brief Handle configuration changes.
   */
  void on_configuration_changed (
    PluginConfiguration * config,
    bool                  generateNewPluginPortsAndParams);

  /**
   * @brief Shows/hides the plugin editor to match @ref uiVisible.
   */
  void on_ui_visibility_changed () override;

private:
  /**
   * @brief Creates and shows the plugin's editor view in a host window.
   */
  void show_editor ();

  /**
   * @brief Hides the host window, keeping the native GUI alive.
   *
   * The editor view stays attached; it is detached by @ref detach_editor on
   * unload.
   */
  void hide_editor ();

  /**
   * @brief Detaches the plugin's editor view and destroys the host window.
   */
  void detach_editor ();

  /**
   * @brief Loads the plugin at the given path.
   *
   * @param path Path to the .vst3 bundle or binary.
   * @param plugin_unique_id Hash of the VST3 class ID (TUID) string, as
   *   generated by Vst3PluginFormat::get_hash_for_range. As a fallback (for
   *   projects saved before the native scanner existed), matching by plugin
   *   name is attempted.
   * @param generate_new_ports Whether to create Zrythm ports from the plugin's
   *   bus layout.
   */
  bool load_plugin (
    const std::filesystem::path &path,
    int64_t                      plugin_unique_id,
    bool                         generate_new_ports = true);
  void unload_current_plugin ();

  void create_ports_from_vst3_component ();

  /**
   * @brief Creates Zrythm parameters from the controller's parameter list.
   *
   * For params already existing (e.g. after deserialization), only the
   * parameter mappings are rebuilt.
   */
  void create_parameters_from_vst3_controller ();

  static constexpr auto kStateKey = "state"sv;
  friend void           to_json (nlohmann::json &j, const Vst3Plugin &p);
  friend void           from_json (const nlohmann::json &j, Vst3Plugin &p);

  std::string save_state_impl () const override;
  void        load_state_impl (const std::string &base64_state) override;

  /**
   * @brief Applies state from a QByteArray to the VST3 plugin.
   */
  void apply_state_from_byte_array (const QByteArray &data);

private:
  class Vst3PluginImpl;
  std::unique_ptr<Vst3PluginImpl> pimpl_;

  /** Pending state to apply after plugin initialization (from JSON). */
  std::optional<QByteArray> state_to_apply_;
};

} // namespace zrythm::plugins
