// SPDX-FileCopyrightText: © 2026 Alexandros Theodotou <alex@zrythm.org>
// SPDX-License-Identifier: LicenseRef-ZrythmLicense

#pragma once

#include <span>
#include <vector>

#include "dsp/audio_bus_configuration.h"
#include "dsp/speaker_arrangement.h"
#include "plugins/plugin.h"

namespace zrythm::plugins
{

/**
 * @brief Native VST3 plugin host implementation.
 *
 * Hosts VST3 plugins directly via the VST3 SDK's IComponent /
 * IAudioProcessor / IEditController interfaces, mirroring how ClapPlugin
 * hosts CLAP plugins. Discovery is done by Vst3PluginFormat.
 */
class Vst3Plugin : public Plugin
{
  Q_OBJECT
  QML_ELEMENT
  QML_UNCREATABLE ("")

public:
  /**
   * @brief Constructor for Vst3Plugin.
   *
   * @param registry Object registry
   * @param host_window_factory Factory for creating plugin host windows
   * @param parent Parent QObject
   */
  Vst3Plugin (
    utils::IObjectRegistry &registry,
    PluginHostWindowFactory host_window_factory,
    QObject *               parent = nullptr);
  Q_DISABLE_COPY_MOVE (Vst3Plugin)
  ~Vst3Plugin () override;

  // ============================================================================
  // Plugin Interface Implementation
  // ============================================================================

  units::sample_u32_t get_single_playback_latency () const override;

  bool hasNativeUi () const override;

  std::span<const PresetEntry> presetEntries () const override;

  /**
   * @brief Returns the hosted component's live audio bus configuration for
   * @p flow, in bus order.
   *
   * Every bus is reported active (this host activates all buses). Returns an
   * empty list when no plugin is loaded.
   */
  std::vector<dsp::AudioBusConfig>
  get_audio_bus_configs (dsp::PortFlow flow) const;

  /**
   * @brief Pushes the given bus arrangements into the plugin via
   * IAudioProcessor::setBusArrangements.
   *
   * Per the VST3 contract this requires an inactive component: if the plugin
   * is processing it is deactivated first and re-prepared afterwards.
   * Arrangements with no VST3 representation (discrete, ambisonics beyond
   * 4th order) leave the corresponding bus unchanged. Must be called on the
   * main thread with the engine paused.
   *
   * @return true if the plugin accepted the request in full. On refusal (or
   * partial acceptance), the accepted per-bus state can be read back with
   * get_audio_bus_configs().
   */
  bool set_bus_arrangements (
    std::span<const dsp::SpeakerArrangement> input_arrangements,
    std::span<const dsp::SpeakerArrangement> output_arrangements)
    [[clang::blocking]];

protected:
  void prepare_plugin_for_processing (
    units::sample_rate_t sample_rate,
    units::sample_u32_t  max_block_length) override;

  void process_impl (
    dsp::graph::ProcessBlockInfo time_info,
    const dsp::ITransport       &transport,
    const dsp::TempoMap         &tempo_map) noexcept override;

  void release_resources_impl () override;

private Q_SLOTS:
  /**
   * @brief Handle configuration changes.
   */
  void on_configuration_changed (
    PluginConfiguration * config,
    bool                  generateNewPluginPortsAndParams);

  /**
   * @brief Shows/hides the plugin editor to match @ref uiVisible.
   */
  void on_ui_visibility_changed () override;

private:
  /**
   * @brief Creates and shows the plugin's editor view in a host window.
   */
  void show_editor ();

  /**
   * @brief Hides the host window, keeping the native GUI alive.
   *
   * The editor view stays attached; it is detached by @ref detach_editor on
   * unload.
   */
  void hide_editor ();

  /**
   * @brief Detaches the plugin's editor view.
   *
   * @param destroy_window Whether to destroy the host window. When false,
   * the window is only hidden: plugin toolkits may still reference the
   * embed parent during their view teardown, so on unload the window is
   * kept alive until the view is fully released (see
   * unload_current_plugin).
   */
  void detach_editor (bool destroy_window = true);

  /**
   * @brief Loads the plugin at the given path.
   *
   * @param path Path to the .vst3 bundle or binary.
   * @param plugin_unique_id Hash of the VST3 class ID (TUID) string, as
   *   generated by get_hash_for_range(). As a fallback (for
   *   projects saved before the native scanner existed), matching by plugin
   *   name is attempted.
   * @param generate_new_ports Whether to create Zrythm ports from the plugin's
   *   bus layout.
   */
  bool load_plugin (
    const std::filesystem::path &path,
    int64_t                      plugin_unique_id,
    bool                         generate_new_ports = true);
  void unload_current_plugin ();

  /**
   * @brief Tears down and re-creates the component, carrying the current
   * state over to the new instance.
   *
   * Handles RestartFlags::kReloadComponent. Must be called on the main
   * thread with processing paused. Ports and parameters are preserved
   * (matched by unique ID); a visible native editor is re-shown
   * afterwards.
   */
  void reload_component ();

  /**
   * @brief Creates Zrythm ports from the component's bus layout.
   *
   * @return false if the component reported an invalid bus layout (failed
   *   getBusInfo or an unsupported channel count); port creation is
   *   incomplete in that case and the load must be aborted.
   */
  bool create_ports_from_vst3_component ();

  /**
   * @brief Pushes the restored ports' bus arrangements into the plugin and
   * reconciles the ports with the accepted configuration.
   *
   * Called at load when the ports were restored from a project instead of
   * created from the component. When the plugin refuses the restored
   * topology, the ports are reconciled to the live layout instead and a
   * warning is logged.
   */
  void restore_saved_bus_arrangements ();

  /**
   * @brief Creates Zrythm parameters from the controller's parameter list.
   *
   * For params already existing (e.g. after deserialization), only the
   * parameter mappings are rebuilt.
   *
   * Called exactly once at load, before processing starts: the realtime
   * mapping is published non-atomically relative to parameter creation, so
   * no call may happen while the audio thread is running.
   */
  void create_parameters_from_vst3_controller ();

  /**
   * @brief Rebuilds the MIDI CC -> ParamID translation table from the
   * controller's IMidiMapping.
   *
   * Called at load and when the plugin reports
   * RestartFlags::kMidiCCAssignmentChanged (e.g. after MIDI learn in the
   * plugin's own UI). Note this does not change parameter exposure at
   * runtime: a newly CC-mapped parameter stays visible (both automation
   * and CC reach it), and a newly unmapped one stays hidden until reload.
   */
  void rebuild_midi_cc_mapping ();

  /**
   * @brief Rebuilds the cached preset list from the controller's
   * program-change parameter and IUnitInfo program lists, notifying via
   * Plugin::notify_presets_rebuilt() when the content changed.
   *
   * The cache is refreshed when the plugin reports a program-list change:
   * RestartFlags::kMidiCCAssignmentChanged for list id/step count changes,
   * IUnitHandler::notifyProgramListChange for list content changes (e.g.
   * the plugin renaming a program).
   */
  void rebuild_preset_list ();

  /**
   * @brief Re-reads the program-change parameter info (id, step count,
   * unit) into the realtime mapping and syncs the main-thread copies.
   */
  void refresh_program_change_param_state ();

  /**
   * @brief Reads the current program from the controller and adopts it as
   * the selection.
   *
   * Out-of-range values reported by the plugin are refused with a warning.
   */
  void adopt_current_program_from_controller ();

  /**
   * @brief Applies a preset selection by queueing a program change on the
   * plugin's kIsProgramChange parameter.
   */
  void apply_preset_impl (const PresetId &id) override;

  /**
   * @brief Notifies the edit controller of a host-initiated parameter
   * change (setParamNormalized wrapped in begin/endEditFromHost).
   *
   * Deferred to the main thread: controller calls must not run inline
   * inside process_impl's realtime context.
   */
  void notify_controller_param_value (
    uint32_t param_id,
    double   normalized_value) noexcept [[clang::nonblocking]];

  static constexpr auto kStateKey = "state"sv;
  friend void           to_json (nlohmann::json &j, const Vst3Plugin &p);
  friend void           from_json (const nlohmann::json &j, Vst3Plugin &p);

  std::string save_state_impl () const override;
  bool        load_state_impl (const std::string &base64_state) override;

  /**
   * @brief Applies state from a QByteArray to the VST3 plugin.
   */
  bool apply_state_from_byte_array (const QByteArray &data);

private:
  class Vst3PluginImpl;
  std::unique_ptr<Vst3PluginImpl> pimpl_;

  /** Pending state to apply after plugin initialization (from JSON). */
  std::optional<QByteArray> state_to_apply_;
};

} // namespace zrythm::plugins
