/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    This header file contains configuration options for the plug-in. If you need to change any of
    these, it'd be wise to do so using the Jucer, rather than editing this file directly...

*/

#ifndef __PLUGINCHARACTERISTICS_D4EFFF1A__
#define __PLUGINCHARACTERISTICS_D4EFFF1A__

#define JucePlugin_Name                 "The Pilgrim"
#define JucePlugin_Desc                 "The Pilgrim"
#define JucePlugin_Manufacturer         "Artican"
#define JucePlugin_ManufacturerCode     'Artc'
#define JucePlugin_PluginCode           'Plgm'
#define JucePlugin_MaxNumInputChannels  2
#define JucePlugin_MaxNumOutputChannels 2
#define JucePlugin_PreferredChannelConfigurations   {1, 1}, {2, 2}
#define JucePlugin_IsSynth              0
#define JucePlugin_IsMidiEffect         0
#define JucePlugin_WantsMidiInput       0
#define JucePlugin_ProducesMidiOutput   0
#define JucePlugin_SilenceInProducesSilenceOut  0
#define JucePlugin_EditorRequiresKeyboardFocus  1
#define JucePlugin_VersionCode          0x20000
#define JucePlugin_VersionString        "2.0.0"
#define JucePlugin_VSTUniqueID          JucePlugin_PluginCode
#define JucePlugin_VSTCategory          kPlugCategEffect
#define JucePlugin_AUMainType           kAudioUnitType_Effect
#define JucePlugin_AUSubType            JucePlugin_PluginCode
#define JucePlugin_AUExportPrefix       ThePilgrim2ProjectAU
#define JucePlugin_AUExportPrefixQuoted "ThePilgrim2ProjectAU"
#define JucePlugin_AUManufacturerCode   JucePlugin_ManufacturerCode
#define JucePlugin_CFBundleIdentifier   com.arcticanaudio.ThePilgrim2
#define JucePlugin_AUCocoaViewClassName ThePilgrim2ProjectAU_V1
#define JucePlugin_RTASCategory         ePlugInCategory_None
#define JucePlugin_RTASManufacturerCode JucePlugin_ManufacturerCode
#define JucePlugin_RTASProductId        JucePlugin_PluginCode

#define JucePlugin_LV2URI               "http://arcticanaudio.com/plugins/thepilgrim"
#define JucePlugin_LV2Category          "PhaserPlugin"
#define JucePlugin_WantsLV2Latency      0
#define JucePlugin_WantsLV2Presets      0
#define JucePlugin_WantsLV2State        0
#define JucePlugin_WantsLV2TimePos      0

#endif   // __PLUGINCHARACTERISTICS_D4EFFF1A__
