/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __VOLUMEDIAL_H_CFF4EBB1__
#define __VOLUMEDIAL_H_CFF4EBB1__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "KnobsBI.h"

//==============================================================================
/**
*/
class Knob : public Slider


{
public:
    //==============================================================================
    Knob();
    ~Knob();

    void paint (Graphics& g) override;
    void setKnobType (int newType);
    void calculateReadoutValue();

    enum KnobType
    {
        defaultType = 0,
        dualFilterType,
        mixType,
        panType,
        gainType,
        totalNumTypes
    };

private:
    //==============================================================================
    Image filterKnobImage, mixKnobImage;
    int frameWidth;
    String readoutText;
    int knobType;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Knob);
};

#endif  // __VOLUMEDIAL_H_CFF4EBB1__
