/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_A5624E04__
#define __PLUGINEDITOR_H_A5624E04__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "PluginProcessor.h"
#include "Knob.h"
#include "BackgroundImage.h"

//==============================================================================
/**
*/
class ThePilgrimAudioProcessorEditor  : public AudioProcessorEditor,
                                        public Slider::Listener,
                                        public Timer
{
public:
    ThePilgrimAudioProcessorEditor (ThePilgrimAudioProcessor* ownerFilter);
    ~ThePilgrimAudioProcessorEditor() override;

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g) override;
    void resized () override;
    void sliderValueChanged (Slider *slider) override;
    void timerCallback() override;

    ThePilgrimAudioProcessor* getProcessor() const
    {
        return static_cast <ThePilgrimAudioProcessor*> (getAudioProcessor());
    }

private:
    Knob filterSlider;
    Knob mixSlider;
    Image bgImage;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ThePilgrimAudioProcessorEditor);
};

#endif  // __PLUGINEDITOR_H_A5624E04__
