/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PHASEBUTTON_H_CFF4EBB1__
#define __PHASEBUTTON_H_CFF4EBB1__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "../Binary Data/UI/button.h"

//==============================================================================
/**
*/
class FancyButton : public TextButton
{
public:
    //==============================================================================
    FancyButton();
    ~FancyButton() override;

    void paint (Graphics& g) override;

private:
    //==============================================================================
    Image buttonImage;
    int frameWidth;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(FancyButton);
};

#endif  // __PHASEBUTTON_H_CFF4EBB1__
