/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    This header file contains configuration options for the plug-in. If you need to change any of
    these, it'd be wise to do so using the Jucer, rather than editing this file directly...

*/

#ifndef __PLUGINCHARACTERISTICS_D4EFFF1A__
#define __PLUGINCHARACTERISTICS_D4EFFF1A__

#define JucePlugin_Name                 "JuceOPL"
#define JucePlugin_Desc                 "JuceOPL"
#define JucePlugin_Manufacturer         "Plainweave Software"
#define JucePlugin_ManufacturerCode     'Pwve'
#define JucePlugin_PluginCode           'JOPL'
#define JucePlugin_MaxNumInputChannels  0
#define JucePlugin_MaxNumOutputChannels 1
#define JucePlugin_PreferredChannelConfigurations   {0, 1}
#define JucePlugin_IsSynth              0
#define JucePlugin_IsMidiEffect         0
#define JucePlugin_WantsMidiInput       1
#define JucePlugin_ProducesMidiOutput   0
#define JucePlugin_SilenceInProducesSilenceOut  0
#define JucePlugin_TailLengthSeconds    0
#define JucePlugin_EditorRequiresKeyboardFocus  0
#define JucePlugin_VersionCode          0x10000
#define JucePlugin_VersionString        "1.0.0"
#define JucePlugin_VSTUniqueID          JucePlugin_PluginCode
#define JucePlugin_VSTCategory          kPlugCategEffect

#define JucePlugin_LV2URI               "https://bsutherland.github.io/JuceOPLVSTi/"
#define JucePlugin_WantsLV2Latency      0
#define JucePlugin_WantsLV2TimePos      0
#define JucePlugin_WantsLV2State        1
#define JucePlugin_WantsLV2Presets      0

#endif   // __PLUGINCHARACTERISTICS_D4EFFF1A__
